export const projectsCards = [
	{
		id: 1,
		img: "../../img/card.jpg",
		name: "Card Music",
		url: "https://github.com/conradojuliosisnero/card-shop-music",
		leyend: "Card",
		span: "Responsive",
		icons: { html: "../../img/html.svg", sass: "../../img/sass.svg" },
	},
	{
		id: 2,
		name: "Componente QR",
		leyend: "Card",
		span: "Responsive",
		url: "https://github.com/conradojuliosisnero/QR-card",
		img: "../../img/qrcomponet.jpg",
		icons: { html: "../../img/html.svg", sass: "../../img/sass.svg" },
	},
	{
		id: 3,
		name: "Card Result",
		leyend: "Card",
		span: "Responsive",
		url: "https://github.com/conradojuliosisnero/card-results",
		img: "../../img/resultados.jpg",
		icons: { html: "../../img/html.svg", sass: "../../img/sass.svg" },
	},
	{
		id: 4,
		name: "Card Shop",
		leyend: "Card",
		span: "Responsive",
		url: "https://github.com/conradojuliosisnero/card-shop",
		img: "../../img/cardshop.png",
		icons: { html: "../../img/html.svg", sass: "../../img/sass.svg" },
	},
	{
		id: 5,
		name: "Encriptador de Texto",
		leyend: "Proyect",
		span: "Responsive",
		url: "https://conradojuliosisnero.github.io/encriptador/",
		img: "../../img/encriptador.png",
		icons: {
			html: "../../img/html.svg",
			sass: "../../img/sass.svg",
			js: "../../img/javascript.svg",
		},
	},
	{
		id: 6,
		name: "App Task",
		leyend: "Proyect",
		url: "https://apptasksite.000webhostapp.com/app-tareas/task.php",
		img: "../../img/app-task.png",
		icons: {
			html: "../../img/html.svg",
			css: "../../img/css.svg",
			js: "../../img/javascript.svg",
			php: "../../img/php.svg",
		},
	},
	{
		id: 7,
		name: "App Movies",
		leyend: "Proyect",
		span: "Responsive",
		url: "https://moviescon.vercel.app/",
		img: "../../img/app-movies.png",
		icons: {
			html: "../../img/html.svg",
			css: "../../img/css.svg",
			js: "../../img/javascript.svg",
		},
	},	
	{
		id: 8,
		name: "To do List",
		leyend: "Proyect",
		span: "Responsive",
		url: "https://app-list-task.vercel.app/",
		img: "../../img/todolist.png",
		icons: {
			html: "../../img/html.svg",
			sass: "../../img/sass.svg",
			js: "../../img/javascript.svg",
		},
	},
];
